name: Build and Push Docker Image

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags (v1.0.0, v2.1.0, etc.)

env:
  GCP_REGION: europe-west2
  GCP_PROJECT_ID: primer-450808
  WORKLOAD_IDENTITY_PROVIDER: projects/primer-450808/locations/global/workloadIdentityPools/primer-github-pool/providers/primer-github-provider
  SERVICE_ACCOUNT: github-actions@primer-450808.iam.gserviceaccount.com
  REGISTRY: europe-west2-docker.pkg.dev/primer-450808/simple-webserver
  IMAGE_NAME: ${{ github.event.repository.name }}-${{ github.ref_name }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker ${{ env.GCP_REGION }}-docker.pkg.dev

      - name: Build Docker image
        run: |
          docker build \
            --build-arg VERSION=${{ github.ref_name }} \
            -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} \
            .

      - name: Push Docker image
        run: |
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
